# Generated by Django 5.1.7 on 2025-03-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airecommendation",
            name="recommended_course",
            field=models.TextField(),
        ),
    ]
